routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => 'install'], function() {
    Route::get('/', ['as' => 'main', 'uses' => 'MainController@redirect']);
    Route::get('locale/{locale}', ['as' => 'change_locale', 'uses' => 'MainController@changeLocale']);

    // Login
    Route::get('login', ['as' => 'get_login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'post_login', 'uses' => 'Auth\LoginController@login']);

    // Forgot Password
    Route::get('password/email', ['as' => 'get_email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'post_email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);

    // Reset Password
    Route::get('password/reset/{token}', ['as' => 'get_reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'post_reset', 'uses' => 'Auth\ResetPasswordController@reset']);

    // Add to Queue
    Route::get('queue', ['as' => 'add_to_queue', 'uses' => 'AddToQueueController@index']);
    Route::post('queue', ['as' => 'post_add_to_queue', 'uses' => 'AddToQueueController@postDept']);

    // Display
    Route::get('display', ['as' => 'display', 'uses' => 'DisplayController@index']);

    // Authenticated
	Route::group(['middleware' => 'auth:users'], function() {
        // Logout
		Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

		// Dashboard
		Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::post('dashboard/settings', ['as' => 'dashboard_store', 'uses' => 'DashboardController@store']);

        // Calls
        Route::get('calls', ['as' => 'calls', 'uses' => 'CallController@index']);
        Route::post('calls', ['as' => 'post_call', 'uses' => 'CallController@newCall']);
        Route::post('calls/recall', ['as' => 'post_recall', 'uses' => 'CallController@recall']);
        Route::post('calls/dept/{department}', ['as' => 'post_dept', 'uses' => 'CallController@postDept']);

        // Department
        Route::resource('departments', 'DepartmentController', ['except' => ['show']]);

        // Counter
        Route::resource('counters', 'CounterController', ['except' => ['show']]);

        //Reports
        Route::group(['prefix' => 'reports', 'as' => 'reports::'], function() {
            // User Report
            Route::get('user', ['as' => 'user', 'uses' => 'UserReportController@index']);
            Route::get('user/{user}/{date}', ['as' => 'user_show', 'uses' => 'UserReportController@show']);

            // Queue list
            Route::get('queuelist/{date}', ['as' => 'queue_list', 'uses' => 'QueueListReportController@index']);

            // Monthly Report
            Route::get('monthly', ['as' => 'monthly', 'uses' => 'MonthlyReportController@index']);
            Route::get('monthly/{department}/{sdate}/{edate}', ['as' => 'monthly_show', 'uses' => 'MonthlyReportController@show']);

            // Statistical Report
            Route::get('statistical', ['as' => 'statistical', 'uses' => 'StatisticalReportController@index']);
            Route::get('statistical/{date}/{user}/{department}/{counter}', ['as' => 'statistical_show', 'uses' => 'StatisticalReportController@show']);

            // Missed
            Route::get('missed-overtime', ['as' => 'missed', 'uses' => 'MissedOvertimeReportController@index']);
            Route::get('missed-overtime/{date}/{user}/{counter}/{type}', ['as' => 'missed_show', 'uses' => 'MissedOvertimeReportController@show']);
        });

        // Users
        Route::get('users/{user}/password', ['as' => 'get_user_password', 'uses' => 'UserController@getPassword']);
        Route::post('users/{user}/password', ['as' => 'post_user_password', 'uses' => 'UserController@postPassword']);
        Route::resource('users', 'UserController', ['except' => ['show', 'edit', 'update']]);

        // Settings
        Route::get('settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);
        Route::post('settings', ['as' => 'post_settings', 'uses' => 'SettingsController@update']);
        Route::post('settings/company', ['as' => 'post_company', 'uses' => 'SettingsController@companyUpdate']);
        Route::post('settings/overmissed', ['as' => 'post_over_missed', 'uses' => 'SettingsController@overmissedUpdate']);
        Route::post('settings/locale', ['as' => 'post_locale', 'uses' => 'SettingsController@localeUpdate']);
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'username', 'email', 'role', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function calls()
	{
		return $this->hasMany('App\Models\Call');
	}

	public function getRoleTextAttribute($value)
	{
		if($this->attributes['role']=='A') return trans('messages.mainapp.role.Administrator');

		return trans('messages.mainapp.role.Staff');
	}

    public function getIsAdminAttribute($value)
	{
		if($this->attributes['role']=='A') return true;

        return false;
	}
}

resources/views/layouts/app.blade.php
@extends('layouts.mainapp')

@section('menu')
    <li class="bold{!! Request::is('dashboard*') ? ' active' : '' !!}"><a href="{{ route('dashboard') }}" class="waves-effect waves-cyan truncate">
        <i class="mdi-hardware-laptop"></i> {{ trans('messages.mainapp.menu.dashboard') }}</a>
    </li>

    <li class="bold{!! Request::is('calls*') ? ' active' : '' !!}"><a href="{{ route('calls') }}" class="waves-effect waves-cyan truncate">
        <i class="mdi-communication-chat"></i> {{ trans('messages.mainapp.menu.call') }}</a>
    </li>

    @can('access', \App\Models\Department::class)
        <li class="bold{!! Request::is('departments*') ? ' active' : '' !!}"><a href="{{ route('departments.index') }}" class="waves-effect waves-cyan truncate">
            <i class="mdi-communication-business"></i> {{ trans('messages.mainapp.menu.department') }}</a>
        </li>
    @endcan

    @can('access', \App\Models\Counter::class)
        <li class="bold{!! Request::is('counters*') ? ' active' : '' !!}"><a href="{{ route('counters.index') }}" class="waves-effect waves-cyan truncate">
            <i class="mdi-action-view-quilt"></i> {{ trans('messages.mainapp.menu.counter') }}</a>
        </li>
    @endcan

    @can('access', \App\Models\User::class)
        <li>
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan truncate{!! Request::is('reports*') ? ' active' : '' !!}"><i class="mdi-editor-insert-chart"></i> {{ trans('messages.mainapp.menu.reports.reports') }}</a>
                    <div class="collapsible-body">
                        <ul>
                            <li{!! Request::is('reports/user*') ? ' class="active"' : '' !!}><a href="{{ route('reports::user') }}" class="truncate"> {{ trans('messages.mainapp.menu.reports.user_report') }}</a></li>
                            <li{!! Request::is('reports/queuelist*') ? ' class="active"' : '' !!}><a href="{{ route('reports::queue_list', ['date' => \Carbon\Carbon::now()->format('d-m-Y')]) }}" class="truncate"> {{ trans('messages.mainapp.menu.reports.queue_list') }}</a></li>
                            <li{!! Request::is('reports/monthly*') ? ' class="active"' : '' !!}><a href="{{ route('reports::monthly') }}" class="truncate"> {{ trans('messages.mainapp.menu.reports.monthly') }}</a></li>
                            <li{!! Request::is('reports/statistical*') ? ' class="active"' : '' !!}><a href="{{ route('reports::statistical') }}" class="truncate"> {{ trans('messages.mainapp.menu.reports.statistical') }}</a></li>
                            <li{!! Request::is('reports/missed-overtime*') ? ' class="active"' : '' !!}><a href="{{ route('reports::missed') }}" class="truncate"> {{ trans('messages.mainapp.menu.reports.missed') }} / {{ trans('messages.mainapp.menu.reports.overtime') }}</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
    @endcan

    @can('access', \App\Models\User::class)
        <li class="bold{!! Request::is('users*') ? ' active' : '' !!}"><a href="{{ route('users.index') }}" class="waves-effect waves-cyan truncate">
            <i class="mdi-social-group"></i> {{ trans('messages.mainapp.menu.users') }}</a>
        </li>
    @endcan

    <li class="bold{!! Request::is('settings*') ? ' active' : '' !!}"><a href="{{ route('settings') }}" class="waves-effect waves-cyan truncate">
        <i class="mdi-action-settings"></i> {{ trans('messages.settings') }}</a>
    </li>
    <br><br>
@endsection

resources/views/layouts/mainapp.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <title>@yield('title') | BrainerDevs Token</title>
        <link rel="icon" href="{{ asset('assets/favicon.ico') }}">
        <link href="{{ asset('assets/css/materialize.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="{{ asset('assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
        @yield('css')
        <link href="{{ asset('assets/css/style.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
    </head>

    <body>
        <div id="loader-wrapper">
            <div id="loader"></div>
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>

        <header id="header" class="page-topbar">
            <div class="navbar-fixed">
                <nav class="navbar-color">
                    <div class="nav-wrapper">
                        <ul class="left">
                            <li><h1 class="logo-wrapper"><a href="{{ route('dashboard') }}" class="brand-logo darken-1"><img src="{{ asset('assets/images/logo_m.png') }}" alt="materialize logo"></a><span class="logo-text">BrainerDevs Token</span></h1></li>
                        </ul>
                        <ul class="right hide-on-med-and-down">
                            <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="{{ asset('assets/images/flag-icons/'.$clocale->image) }}" alt="{{ $clocale->name }}" /></a></li>
                            <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown"><i class="mdi-editor-insert-link"></i></a></li>
                            <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a></li>
                        </ul>
                        <ul id="translation-dropdown" class="dropdown-content" style="max-height:250px">
                            <li><h5 style="font-size:1rem;padding:0 1rem 0 1rem;font-weight:500">{{ trans('messages.mainapp.select_language') }}</h5></li>
                            <li class="divider"></li>
                            @foreach($languages as $language)
                                <li{!! ($clocale->code==$language->code)?' class="active"':'' !!}><a href="{{ route('change_locale', ['locale' => $language->code]) }}"><img src="{{ asset('assets/images/flag-icons/'.$language->image) }}" alt="{{ $language->name }}" />  <span class="language-select">{{ trans('messages.locales.'.$clocale->code.'.'.$language->code) }}</span></a></li>
                            @endforeach
                        </ul>
                        <ul id="notifications-dropdown" class="dropdown-content">
                            <li><h5>LINKS</h5></li>
                            <li class="divider"></li>
                            <li><a href="{{ route('display') }}" target="_blank" style="font-weight:400">{{ trans('messages.mainapp.display_url') }}</a></li>
                            <li><a href="{{ route('add_to_queue') }}" target="_blank" style="font-weight:400">{{ trans('messages.mainapp.issue_url') }}</a></li>
                        </ul>
                        <ul class="right hide-on-med-and-down">
                            <span class="truncate" style="margin-right:20px;font-size:19px">{{ $company_name }}</span>
                        </ul>
                    </div>
                </nav>
            </div>
        </header>

        <div id="main">
            <div class="wrapper">
                <aside id="left-sidebar-nav">
                    <ul id="slide-out" class="side-nav fixed leftside-navigation">
                        <li class="user-details cyan darken-2">
                            <div class="row">
                                <div class="col col s4 m4 l4">
                                    <img src="{{ asset('assets/images/avatar.jpg') }}" alt="" class="circle responsive-img valign profile-image">
                                </div>
                                <div class="col col s8 m8 l8">
                                    <ul id="profile-dropdown" class="dropdown-content">
                                        <li><a href="{{ route('settings') }}"><i class="mdi-action-settings"></i> {{ trans('messages.settings') }}</a></li>
                                        <li class="divider"></li>
                                        <li><a class="frmsubmit" href="{{ route('logout') }}" message="false" method="post"><i class="mdi-hardware-keyboard-tab"></i> {{ trans('messages.mainapp.logout') }}</a></li>
                                    </ul>
                                    <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn truncate" href="#" data-activates="profile-dropdown">
                                        {{ $user->name }}<i class="mdi-navigation-arrow-drop-down right"></i>
                                    </a>
                                    <p class="user-roal">{{ $user->role_text }}</p>
                                </div>
                            </div>
                        </li>
                        @yield('menu')
                    </ul>
                    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only teal lighten-1"><i class="mdi-navigation-menu"></i></a>
                </aside>

                <section id="content">
                    @yield('content')
                </section>
            </div>
        </div>

        <footer class="page-footer">
            <div class="footer-copyright">
                <div class="container">
                    <span>Powered by <a class="grey-text text-lighten-3" href="http://www.brainerdevs.com" target="_blank">BrainerDevs LLC.</a> All rights reserved.</span>
                    <span class="right"> <span class="grey-text text-lighten-3">Version</span> 1.0</span>
                </div>
            </div>
        </footer>
        @yield('print')
        <script type="text/javascript" src="{{ asset('assets/js/plugins/jquery-1.11.2.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/materialize.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/plugins/jquery-validation/jquery.validate.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/select2.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/plugins.min.js') }}"></script>
        @yield('script')
        <script>
            $(function() {
                $('#main').css({'min-height': $(window).height()-134+'px'});
                $(window).resize(function() {
                    $('#main').css({'min-height': $(window).height()-134+'px'});
                });
                $('#translation-dropdown').perfectScrollbar();
                $('select').each(function() {
                    if(!$(this).parent().hasClass('picker__header')) {
                        $(this).select2();
                    }
                });
            });
            $(".frmsubmit").on("click",function(e) {
                var message = 'Are you sure you want to delete?';
                if(e.currentTarget.attributes.message!=undefined) message = e.currentTarget.attributes.message.value;
                var cnfrm = true;
                if(e.currentTarget.attributes.message!=undefined && e.currentTarget.attributes.message.value=='false') cnfrm = false;
                if (cnfrm) {
                    if(confirm(message)) {
                        e.preventDefault();
                        var myForm = '<form id="hidfrm" action="'+e.currentTarget.attributes.href.value+'" method="post">{{ csrf_field() }}<input type="hidden" name="_method" value="'+e.currentTarget.attributes.method.value+'"></form>';
                        $('body').append(myForm);
                        myForm = $('#hidfrm');
                        myForm.submit();
                    }
                } else {
                    e.preventDefault();
                    var myForm = '<form id="hidfrm" action="'+e.currentTarget.attributes.href.value+'" method="post">{{ csrf_field() }}<input type="hidden" name="_method" value="'+e.currentTarget.attributes.method.value+'"></form>';
                    $('body').append(myForm);
                    myForm = $('#hidfrm');
                    myForm.submit();
                }
                return false;
            });
            @if(!Request::is('calls*'))
                $(document).ajaxStart(function() {
                    $("body").removeClass('loaded');
                    Pace.restart();
                });
                $(document).ajaxStop(function() {
                    $("body").addClass('loaded');
                });
            @endif
        </script>
        @include('common.messages')
    </body>
</html>

resources/views/layouts/mainappqueue.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <title>@yield('title') | BrainerDevs Token</title>
        <link rel="icon" href="{{ asset('assets/favicon.ico') }}">
        <link href="{{ asset('assets/css/materialize.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="{{ asset('assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
        @yield('css')
        <link href="{{ asset('assets/css/style.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
    </head>

    <body>
        <div id="loader-wrapper">
            <div id="loader"></div>
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>

        <header id="header" class="page-topbar">
            <div class="navbar-fixed">
                <nav class="navbar-color">
                    <div class="nav-wrapper">
                        <ul class="left">
                            <li><h1 class="logo-wrapper"><a href="{{ route('dashboard') }}" class="brand-logo darken-1"><img src="{{ asset('assets/images/logo_m.png') }}" alt="materialize logo"></a><span class="logo-text">BrainerDevs Token</span></h1></li>
                        </ul>
                        <ul class="right hide-on-med-and-down">
                            <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a></li>
                        </ul>
                        <ul class="right">
                            <span class="truncate" style="margin-right:20px;font-size:20px">{{ $settings->name }}</span>
                        </ul>
                    </div>
                </nav>
            </div>
        </header>

        <div id="main" style="padding:15px;padding-bottom:0">
            <div class="wrapper">
                <section id="content">
                    @yield('content')
                </section>
            </div>
        </div>

        <footer class="page-footer" style="padding:0;margin-top:0">
            <div class="footer-copyright">
                <div class="container">
                    <span>Powered by <a class="grey-text text-lighten-3" href="http://www.brainerdevs.com" target="_blank">BrainerDevs LLC.</a> All rights reserved.</span>
                    <span class="right"> <span class="grey-text text-lighten-3">Version</span> 2.1.1</span>
                </div>
            </div>
        </footer>
        @yield('print')
        <script type="text/javascript" src="{{ asset('assets/js/plugins/jquery-1.11.2.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/materialize.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/plugins.min.js') }}"></script>
        @yield('script')
        @include('common.messages')
    </body>
</html>